import type { Exercise } from './index.js';

type Muscle = Exercise['primaryMuscles'][number];
type Tag = Exercise['tag'];

function exercise(
  number: number,
  nameRu: string,
  nameEn: string,
  aliases: string[],
  tag: Tag,
  primaryMuscles: Muscle[],
  secondaryMuscles: Muscle[],
  equipment: string[],
  video: { title: string; url: string },
): Exercise {
  return {
    id: `10000000-0000-4000-8000-${String(number).padStart(12, '0')}`,
    scope: 'global',
    nameRu,
    nameEn,
    aliases,
    tag,
    primaryMuscles,
    secondaryMuscles,
    equipment,
    videos: [video],
  };
}

export const retiredGlobalExerciseIds = new Set([
  '10000000-0000-4000-8000-000000000011',
  '10000000-0000-4000-8000-000000000012',
]);

export const globalExerciseCatalog: Exercise[] = [
  exercise(
    1,
    'Тяга верхнего блока прямым хватом',
    'Overhand-grip lat pulldown',
    ['тяга верхнего блока', 'верхний блок', 'lat pulldown'],
    'normal',
    ['back'],
    ['biceps', 'rear_delt'],
    ['cable machine'],
    {
      title: 'Техника тяги верхнего блока',
      url: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    },
  ),
  exercise(
    2,
    'Разведение гантелей в стороны стоя',
    'Standing dumbbell lateral raise',
    ['разведения гантелей в стороны', 'махи в стороны', 'lateral raise'],
    'normal',
    ['middle_delt'],
    [],
    ['dumbbells'],
    {
      title: 'Техника разведений гантелей',
      url: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    },
  ),
  exercise(
    3,
    'Жим штанги лёжа на горизонтальной скамье',
    'Flat barbell bench press',
    ['жим лёжа', 'жим штанги лёжа', 'жим штанги на прямой скамье', 'bench press'],
    'mighty',
    ['chest'],
    ['triceps', 'front_delt'],
    ['barbell', 'bench'],
    {
      title: 'Техника жима штанги лёжа',
      url: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    },
  ),
  exercise(
    4,
    'Сгибание рук с гантелями стоя',
    'Standing dumbbell curl',
    ['сгибание рук с гантелями', 'сгибание рук', 'сгибания на бицепс', 'dumbbell curl'],
    'normal',
    ['biceps'],
    [],
    ['dumbbells'],
    {
      title: 'Техника сгибаний с гантелями',
      url: 'https://www.youtube.com/watch?v=ykJmrZ5v0Oo',
    },
  ),
  exercise(
    5,
    'Приседания со штангой на спине',
    'Barbell back squat',
    ['приседания со штангой', 'присед', 'barbell squat', 'squat'],
    'normal',
    ['quadriceps'],
    ['hamstrings', 'glutes', 'core'],
    ['barbell', 'rack'],
    {
      title: 'Техника приседаний со штангой',
      url: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
    },
  ),
  exercise(
    6,
    'Разгибание рук на верхнем блоке стоя',
    'Standing cable triceps pushdown',
    ['разгибание рук на блоке', 'трицепс на блоке', 'cable triceps extension', 'pushdown'],
    'normal',
    ['triceps'],
    [],
    ['cable machine'],
    {
      title: 'Техника разгибаний рук на блоке',
      url: 'https://www.youtube.com/watch?v=2-LAMcpzODU',
    },
  ),
  exercise(
    7,
    'Румынская тяга со штангой',
    'Barbell Romanian deadlift',
    ['румынская тяга', 'румынская становая тяга', 'румынка', 'romanian deadlift', 'rdl'],
    'cringe',
    ['hamstrings'],
    ['glutes', 'back', 'core'],
    ['barbell'],
    {
      title: 'Техника румынской тяги',
      url: 'https://www.youtube.com/watch?v=JCXUYuzwNrM',
    },
  ),
  exercise(
    8,
    'Тяга горизонтального блока сидя',
    'Seated cable row',
    ['тяга горизонтального блока', 'горизонтальный блок', 'горизонтальная тяга в тренажере'],
    'mighty',
    ['back'],
    ['biceps', 'rear_delt'],
    ['cable machine'],
    {
      title: 'Техника тяги горизонтального блока',
      url: 'https://www.youtube.com/watch?v=GZbfZ033f74',
    },
  ),
  exercise(
    9,
    'Жим штанги стоя',
    'Standing barbell overhead press',
    ['армейский жим', 'overhead press', 'ohp'],
    'mighty',
    ['front_delt', 'middle_delt'],
    ['triceps', 'core'],
    ['barbell'],
    {
      title: 'Техника жима штанги стоя',
      url: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
    },
  ),
  exercise(
    10,
    'Болгарские выпады с гантелями',
    'Dumbbell Bulgarian split squat',
    ['болгарские выпады', 'болгарские приседания', 'split squat'],
    'cringe',
    ['quadriceps'],
    ['hamstrings', 'glutes', 'core'],
    ['dumbbells', 'bench'],
    {
      title: 'Техника болгарских выпадов',
      url: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
    },
  ),
  exercise(
    13,
    'Жим гантелей лёжа на горизонтальной скамье',
    'Flat dumbbell bench press',
    ['жим гантелей лёжа на грудь', 'жим гантелей лёжа', 'жим гантелей на прямой скамье'],
    'mighty',
    ['chest'],
    ['triceps', 'front_delt'],
    ['dumbbells', 'bench'],
    {
      title: 'Техника жима гантелей лёжа',
      url: 'https://www.youtube.com/watch?v=VmB1G1K7v94',
    },
  ),
  exercise(
    14,
    'Сведение рук в тренажёре «бабочка»',
    'Machine pec deck fly',
    ['сведение рук в тренажёре', 'бабочка на грудь', 'пэк дек', 'пэкдэк', 'pec deck fly'],
    'mighty',
    ['chest'],
    ['front_delt'],
    ['machine'],
    {
      title: 'Техника сведений рук в тренажёре',
      url: 'https://www.youtube.com/watch?v=Z57CtFmRMxA',
    },
  ),
  exercise(
    15,
    'Сведение рук в кроссовере стоя',
    'Standing cable crossover',
    ['сведение рук в кроссовере', 'кроссовер на грудь', 'сведение рук на грудь'],
    'mighty',
    ['chest'],
    ['front_delt'],
    ['cable machine'],
    {
      title: 'Техника сведений рук в кроссовере',
      url: 'https://www.youtube.com/watch?v=taI4XduLpTk',
    },
  ),
  exercise(
    16,
    'Подтягивания прямым хватом',
    'Overhand-grip pull-up',
    ['подтягивания', 'подтягивание', 'pull up', 'pull-up'],
    'normal',
    ['back'],
    ['biceps', 'rear_delt'],
    ['pull-up bar'],
    {
      title: 'Техника подтягиваний',
      url: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    },
  ),
  exercise(
    17,
    'Жим ногами в тренажёре',
    'Machine leg press',
    ['жим ногами', 'leg press'],
    'normal',
    ['quadriceps'],
    ['hamstrings', 'glutes'],
    ['machine'],
    {
      title: 'Техника жима ногами',
      url: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    },
  ),
  exercise(
    18,
    'Жим штанги лёжа на наклонной скамье',
    'Incline barbell bench press',
    [
      'жим штанги лежа на наклонной скамье',
      'жим лежа на наклонной скамье',
      'наклонный жим штанги',
      'жим штанги лёжа на наклонной скамье 30°',
      'incline bench press',
    ],
    'mighty',
    ['chest'],
    ['triceps', 'front_delt'],
    ['barbell', 'incline bench'],
    {
      title: 'Техника наклонного жима штанги',
      url: 'https://www.youtube.com/watch?v=SrqOu55lrYU',
    },
  ),
  exercise(
    19,
    'Пуловер на верхнем блоке стоя',
    'Standing cable pullover',
    ['пуловер', 'пуловер в кроссовере', 'cable pullover', 'straight-arm pulldown'],
    'normal',
    ['back'],
    ['triceps', 'core'],
    ['cable machine'],
    {
      title: 'Техника пуловера на верхнем блоке',
      url: 'https://www.youtube.com/watch?v=32auHIqgEoM',
    },
  ),
  exercise(
    20,
    'Разведение гантелей лёжа на наклонной скамье',
    'Incline prone dumbbell reverse fly',
    ['разведение рук на наклонной скамье', 'разведения в наклоне лёжа'],
    'normal',
    ['rear_delt'],
    ['back'],
    ['dumbbells', 'incline bench'],
    {
      title: 'Техника разведений гантелей на наклонной скамье',
      url: 'https://www.youtube.com/watch?v=bMD474hAjDE',
    },
  ),
  exercise(
    21,
    'Сгибание рук в тренажёре Скотта',
    'Machine preacher curl',
    ['тренажер скотта', 'тренажёр скотта', 'сгибания рук в тренажере скотта'],
    'normal',
    ['biceps'],
    [],
    ['machine'],
    {
      title: 'Техника сгибаний рук в тренажёре Скотта',
      url: 'https://www.youtube.com/watch?v=R-8Sa0_qiws',
    },
  ),
  exercise(
    22,
    'Тяга канатной рукояти к лицу',
    'Rope cable face pull',
    ['лицевая тяга', 'face pull', 'тяга к лицу'],
    'normal',
    ['rear_delt'],
    ['back', 'biceps'],
    ['cable machine', 'rope'],
    {
      title: 'Техника тяги канатной рукояти к лицу',
      url: 'https://www.youtube.com/watch?v=wnPX6Fwe-Fg',
    },
  ),
  exercise(
    23,
    'Гиперэкстензия на римском стуле',
    'Roman chair back extension',
    ['гиперэкстензия', 'back extension'],
    'normal',
    ['back'],
    ['hamstrings', 'glutes', 'core'],
    ['roman chair'],
    {
      title: 'Техника гиперэкстензии на римском стуле',
      url: 'https://www.youtube.com/watch?v=EiTg8Q4KKpg',
    },
  ),
  exercise(
    24,
    'Жим от груди в тренажёре сидя',
    'Seated machine chest press',
    ['чест пресс', 'жим от груди в тренажере', 'machine chest press'],
    'normal',
    ['chest'],
    ['triceps', 'front_delt'],
    ['machine'],
    {
      title: 'Техника жима от груди в тренажёре',
      url: 'https://www.youtube.com/watch?v=n8TOta_pfr4',
    },
  ),
  exercise(
    25,
    'Разгибание рук с канатной рукоятью из-за головы',
    'Overhead rope cable triceps extension',
    [
      'разгибание рук с канатами из-за головы',
      'разгибания рук на блоке из-за головы',
      'разгибание рук на блоке из-за головы',
    ],
    'normal',
    ['triceps'],
    [],
    ['cable machine', 'rope'],
    {
      title: 'Техника разгибаний рук с канатной рукоятью из-за головы',
      url: 'https://www.youtube.com/watch?v=SLYwsE_W1eM',
    },
  ),
  exercise(
    26,
    'Тяга верхнего блока обратным хватом',
    'Reverse-grip lat pulldown',
    ['обратная тяга верхнего блока', 'reverse grip pulldown'],
    'normal',
    ['back'],
    ['biceps', 'rear_delt'],
    ['cable machine'],
    {
      title: 'Техника тяги верхнего блока обратным хватом',
      url: 'https://www.youtube.com/watch?v=IUX3RuWsYNM',
    },
  ),
  exercise(
    27,
    'Жим гантелей стоя',
    'Standing dumbbell shoulder press',
    ['жим гантелей над головой', 'dumbbell overhead press'],
    'normal',
    ['front_delt', 'middle_delt'],
    ['triceps', 'core'],
    ['dumbbells'],
    {
      title: 'Техника жима гантелей стоя',
      url: 'https://www.youtube.com/watch?v=B-aVuyhvLHU',
    },
  ),
  exercise(
    28,
    'Сгибание ног лёжа в тренажёре',
    'Lying machine leg curl',
    ['сгибание ног в тренажере', 'lying leg curl'],
    'normal',
    ['hamstrings'],
    [],
    ['machine'],
    {
      title: 'Техника сгибания ног лёжа в тренажёре',
      url: 'https://www.youtube.com/watch?v=vl5nUdE9mWM',
    },
  ),
  exercise(
    29,
    'Тяга одной рукой в кроссовере сидя',
    'Seated one-arm cable row',
    ['тяга арни', 'тяга арни style', 'тяга одной рукой сидя'],
    'normal',
    ['back'],
    ['biceps', 'rear_delt'],
    ['cable machine'],
    {
      title: 'Техника тяги одной рукой в кроссовере сидя',
      url: 'https://www.youtube.com/watch?v=1jN6qeXdvWA',
    },
  ),
  exercise(
    30,
    'Отведение руки в наклоне на нижнем блоке',
    'Bent-over one-arm cable rear-delt raise',
    ['отведение руки в наклоне в кроссовере', 'rear delt cable raise'],
    'normal',
    ['rear_delt'],
    [],
    ['cable machine'],
    {
      title: 'Техника отведения руки в наклоне на нижнем блоке',
      url: 'https://www.youtube.com/watch?v=MqjrUAZRNAk',
    },
  ),
  exercise(
    31,
    'Французский жим с гантелями лёжа',
    'Lying dumbbell triceps extension',
    ['скулкрашер с гантелями', 'dumbbell skullcrusher'],
    'normal',
    ['triceps'],
    [],
    ['dumbbells', 'bench'],
    {
      title: 'Техника французского жима с гантелями лёжа',
      url: 'https://www.youtube.com/watch?v=ernSa92jYKc',
    },
  ),
  exercise(
    32,
    'Сгибание рук на нижнем блоке стоя',
    'Standing cable biceps curl',
    ['сгибание рук на блоке', 'cable curl'],
    'normal',
    ['biceps'],
    [],
    ['cable machine'],
    {
      title: 'Техника сгибания рук на нижнем блоке',
      url: 'https://www.youtube.com/watch?v=2MUEL4nL6hA',
    },
  ),
  exercise(
    33,
    'Разгибание ног сидя в тренажёре',
    'Seated machine leg extension',
    ['разгибание ног', 'leg extension'],
    'normal',
    ['quadriceps'],
    [],
    ['machine'],
    {
      title: 'Техника разгибания ног в тренажёре',
      url: 'https://www.youtube.com/watch?v=swZQC689o9U',
    },
  ),
  exercise(
    34,
    'Подтягивания обратным хватом',
    'Reverse-grip pull-up',
    ['подтягивания на бицепс', 'chin up', 'chin-up'],
    'normal',
    ['back'],
    ['biceps'],
    ['pull-up bar'],
    {
      title: 'Техника подтягиваний обратным хватом',
      url: 'https://www.youtube.com/watch?v=xMhMXRi7SMY',
    },
  ),
  exercise(
    35,
    'Тяга канатной рукояти к подбородку',
    'Rope cable upright row',
    ['тяга к подбородку в кроссовере', 'cable upright row'],
    'normal',
    ['middle_delt'],
    ['biceps'],
    ['cable machine', 'rope'],
    {
      title: 'Техника тяги канатной рукояти к подбородку',
      url: 'https://www.youtube.com/watch?v=XoI1t4DqBRY',
    },
  ),
  exercise(
    36,
    'Разведение рук в тренажёре «обратная бабочка»',
    'Machine reverse pec deck fly',
    ['обратный пэкдэк', 'обратный пэк дек', 'reverse pec deck'],
    'normal',
    ['rear_delt'],
    ['back'],
    ['machine'],
    {
      title: 'Техника разведений в тренажёре «обратная бабочка»',
      url: 'https://www.youtube.com/watch?v=dC7jhEk-29A',
    },
  ),
  exercise(
    37,
    'Отведение бёдер сидя в тренажёре',
    'Seated machine hip abduction',
    ['отведение бедер в тренажере сидя', 'hip abduction'],
    'normal',
    ['glutes'],
    [],
    ['machine'],
    {
      title: 'Техника отведения бёдер в тренажёре',
      url: 'https://www.youtube.com/watch?v=Nw09BzZPyVs',
    },
  ),
  exercise(
    38,
    'Сведение бёдер сидя в тренажёре',
    'Seated machine hip adduction',
    ['сведение бедер в тренажере сидя', 'hip adduction'],
    'normal',
    ['adductors'],
    [],
    ['machine'],
    {
      title: 'Техника сведения бёдер в тренажёре',
      url: 'https://www.youtube.com/watch?v=GmRSV_n2E_0',
    },
  ),
  exercise(
    39,
    'Скручивания на наклонной скамье',
    'Incline bench crunch',
    ['скамья наклонная для пресса', 'incline sit-up bench'],
    'normal',
    ['core'],
    [],
    ['incline bench'],
    {
      title: 'Техника скручиваний на наклонной скамье',
      url: 'https://www.youtube.com/watch?v=FRzQXeN1hro',
    },
  ),
  exercise(
    40,
    'Сгибание рук со штангой стоя',
    'Standing barbell curl',
    ['сгибание рук со штангой', 'barbell curl'],
    'normal',
    ['biceps'],
    [],
    ['barbell'],
    {
      title: 'Техника сгибания рук со штангой',
      url: 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
    },
  ),
  exercise(
    41,
    'Скручивания в тренажёре для пресса',
    'Machine abdominal crunch',
    ['пресс-машина ultra', 'ultra abdominal crunch machine'],
    'normal',
    ['core'],
    [],
    ['machine'],
    {
      title: 'Техника скручиваний в тренажёре',
      url: 'https://www.youtube.com/watch?v=_O1xunCfYEM',
    },
  ),
];
